apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      daniel:
        description: "foo"
        reguired: true
        default: "bar"
        type: String
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo The value for bar is ${{inputs.daniel}}
env:
  foo: bar
  input1: "1031"
