apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      command:
        description: foo
        reguired: true
        type: String
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: What is my name?
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "The value for bar is $NAME"
        env:
          NAME: "Daniel"
